name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: yarn

      - name: Snapshot
        run: yarn changeset version --snapshot

      - name: Collect all the packages
        id: package_list
        run: |
          echo 'LIST<<EOF' >> $GITHUB_OUTPUT
          bash list.sh >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Publish
        run: yarn changeset publish --tag alpha --no-git-tag --snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Published packages

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            Published packages

            ```
            ${{ steps.package_list.outputs.LIST }}
            ```


