name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version --snapshot $GITHUB_SHA
          publish: yarn changeset publish --tag alpha --no-git-tag --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.changesets.outputs.published == 'true'
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            Published packages

            ```
            ${{ steps.changesets.outputs.publishedPackages }}
            ```

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.changesets.outputs.published != 'true'
        with:
          hide: true
          hide_classify: "OUTDATED"


