name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  snapshot:
    uses: ./.github/workflows/snapshot.yml
    if: github.event.pull_request.title != 'Version Packages'
    permissions:
      contents: write
      packages: write
    with:
      ref: ${{ github.ref }}

  comment:
    runs-on: ubuntu-latest
    needs: [snapshot]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Format package list'
        id: format
        run: |
          echo 'packagesList<<EOF' >> $GITHUB_OUTPUT
          echo "$PUBLISHED_PACKAGES" | awk '{print "yarn add " $0}' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          PUBLISHED_PACKAGES: ${{ needs.snapshot.outputs.publishedPackages }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: needs.snapshot.outputs.numberOfPackages != '0'
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            Published packages

            ```
            ${{ steps.format.outputs.packagesList }}
            ```

      - uses: marocchino/sticky-pull-request-comment@v2
        if: needs.snapshot.outputs.numberOfPackages == '0'
        with:
          hide: true
          hide_classify: "OUTDATED"


