name: Slash Commands

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${NAME}"
        env:
          NAME: ${{ github.repository }}
