name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://npm.pkg.github.com"

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        id: summary
        run: |
          echo 'PAYLOAD<<EOF' >> $GITHUB_OUTPUT
          node slack.js >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}

      - name: Output
        run: |
          echo $PAYLOAD
        env:
          PAYLOAD: ${{ steps.summary.outputs.payload }}
